version: '3.7'

services:
  jekyll_dev:
    image: jekyll/jekyll:latest
    restart: always
    command: jekyll serve /srv/jekyll/ --watch --force_polling --verbose
    networks:
      - frontend
    volumes:
      - ./jekyll:/srv/jekyll
    labels:
      - "traefik.backend=${podName}-jekyll_dev"
      - "traefik.frontend.rule=Host:${hostRuleDev}"
      - "traefik.docker.network=${podName}_frontend"
      - "traefik.port=4000"

networks:
  frontend:
