version: '3.7'

services:
  jekyll_prod:
    build: .
    image: ${podName}-jekyll_prod
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.${podName}.rule=Host(`${hostRule}`)
      - traefik.http.routers.${podName}.entrypoints=websecure
      - traefik.http.services.${podName}.loadbalancer.server.port=80
      - traefik.docker.network=${podName}_frontend
    networks:
      - frontend
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.${podName}.rule=Host(`${hostRule}`)
        - traefik.http.routers.${podName}.entrypoints=websecure
        - traefik.http.services.${podName}.loadbalancer.server.port=80
        - traefik.docker.network=${podName}_frontend

networks:
  frontend:
