version: '3.7'

services:
  jekyll_prod:
    build: .
    image: ${podName}-jekyll_prod
    restart: always
    ports:
    - 80:80
    networks:
      - frontend
    # Deploy block for docker swarm mode only - ignored by docker-compose
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
