version: '3.7'

services:
  jekyll_dev:
    image: jekyll/jekyll:latest
    restart: always
    command: jekyll serve /srv/jekyll/ --watch --force_polling --verbose
    networks:
      - frontend
    volumes:
      - ./jekyll:/srv/jekyll
    ports:
    - 4000:4000

networks:
  frontend:
